[package]
name = "steel-yaml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.5.0"

[rust]
debuginfo-level = 1

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "event_processing"
harness = false

[profile.release]
opt-level=1
debug = true