[package]
name = "yam-dark-core"
version = "0.1.0"
edition = "2021"
authors = ["Ygg01 <y.laughing.man.y@gmail.com>"]
keywords = ["yaml", "simd", "parser"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

[features]
no-inline = []